### ISSUE TITLE
Handling of events that fail validation.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#1]
See TODO here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L899

_getManifestFromPeer calls [_getEventFromPeer](https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L790) which puts events from the peer directly into storage without first validating the event.

During [_gossipWith](https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L295), events received from peers are put through the `events.add` API which *should* be validating events [here](https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/events.js#L92)

It seems like it would be a good idea to validate *all* events before putting them into storage.  However, it is also true that a particular event could be *invalidated* by a config change before the event reaches consensus and is included in a block. (e.g. the event is signed by two parties, but the new configuration requires events to be signed by three parties).

To complicate matters further, events my not be validated due to variety of temporary network failures (e.g. unable to retrieve a context, unable to dereference a public key)

**Comment by dlongley** [comment]
Let's try and boil these problems down:

***For before consensus has been reached:***

If an event can't be validated (for any reason), reject the manifest. If enough other nodes reject the manifest, it won't reach consensus.

***For after consensus has been reached:***

If an event can't be validated because of some temporary failure, keep trying again indefinitely.
If an event can't be validated because of a hard error with the current config, etc. Then reject the manifest. We'll need two different classes of errors to make this work.

Properly operating nodes should never vote for a manifest with invalid events (Note: I don't think this requires reprocessing all of the events just prior to casting a vote but I don't remember why). If they do, their vote should be ignored by other nodes based on the above.

If we really do need to revalidate events for some reason, due to config changes, then what we can do is mark all events that do not have consensus as requiring revalidation whenever a new config block comes in. But I thought we had already incorporated something into the algorithm to account for this.
