### ISSUE TITLE
Validate Status

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#11]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/client.js#L48

@dlongley this needs more explanation.

**Comment by dlongley** [comment]
We should validate the status we received. This may mean that we don't need to do that election validation later because we can just do it all here. Essentially, we just need to do JSON validation on the entire status we received --- so valid `consensusPhase`, event hashes (if present), election stuff (if present), so on.

**Comment by mattcollier** [comment]
Combining this issue with: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/issues/9
