### ISSUE TITLE
Voter signature verification

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#13]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/voters.js#L41

TODO: need a method for voter signature verification whereby the public
key for a voter will be retrieved from the blockchain and verified against
its voter ID (and cached for future use?)

@dlongley needs more explanation.

**Comment by dlongley** [comment]
Hmm, what we wanted here was a place to insert the actual public keys into the blockchain for full auditability via the blockchain itself. It would also really speed things up because you could get previously verified public keys from your own in-database blockchain instead of having to hit the interwebs.

The difficulty is in getting the public keys into the blockchain without causing severe bloat, i.e. putting them in there just once. One option is this:

1. Add a `continuity2017_publicKey` collection.
2. Whenever we are retrieving a public key, hit that collection first to get it -- and if it's a miss, get it from the interwebs and store it in there.
3. Add a method to get a public key from block storage (add the method to this module). This method should walk backwards through any continuity-based blocks looking for a public key that matches the query (which is for `publicKey.owner === voterId`).
4. When writing a block, add a `publicKey` array that adds the public key for every election vote and every signed event in the block -- **if** the public key cannot be retrieved using the method created for item 3 (and, instead, it has to be pulled from the new public key collection where it should now already be).

This should give us both public key caching during gossip and voting as well as auditability in the block chain.

Key rotation (which we aren't implementing now, but hopefully in the near future) involves getting a new voter ID and including a `sameAs` predicated and signing it with your old key (that's partially implemented already I think -- but not used yet).
