### ISSUE TITLE
Track twoThirdsMajority separately

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#20]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L226

TODO: it's possible that the roll-call votes were discarded, so
we also need to be keeping track, on our own, separately, whether
or not we've received twoThirdsMajority of block status's that
are set to `consensus` with the same block hash (or same set of
events -- these must be equivalent), if so, we have consensus and
don't need the roll call votes ... we can generate the roll-call
manifest using the event votes we've collected where
`status.consensusPhase === 'consensus'`.

@dlongley needs explanation.

**Comment by dlongley** [comment]
So "roll call votes" are ephemeral. We don't currently drop them in the implementation, but they can be dropped. We need to ensure that we implement something so that when they have been dropped (and we can't acquire them from any peers at all), that we can reproduce what manifest they would have voted on. That "event vote" manifest is just the collection of all of the event votes that counted in the block that achieved consensus -- which we receive whenever we get a block status with a `consensusPhase` of `consensus`.

I'm not sure how we want to go about tracking this. Here's one way we could do it:

In `_gossipWith`, after we certify the votes, if the block status had a `consensusPhase` of `consensus` we write a non-consensus block into storage. We include the event vote manifest hash (after we compute it by hashing all of the sorted event vote hashes together (https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L837)) as a key that maps to a count of 1. If the block is already in storage, we just do an `$inc` on that field in the meta.

Then, we incorporate a check on that field into where we tally the roll call votes to determine if we have a winning manifest here:

https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L192-L193

We make a change where if the result of that tally function is `null` (meaning there is no `manifestHash` that won) we run an extra check via a database query on storage to see if any non-consensus block with the expected `blockHeight` has an appropriate meta field with a count that meets twoThirds majority threshold. If so, we return that `manifestHash` as the winner.

Lastly, we'd need to update the `writeBlock` section to flip the consensus flag if a duplicate block is found. So we'd try to write the block, and if it fails due to a duplicate, we'd run an update that would only set the consensus flag if it wasn't already set.

I'm open to other ways to accomplish this. We should also postpone it until other lower hanging fruit is done. It may sound more complicated than it actually is --- it's a matter of producing a manifest hash when we see `consensusPhase` === `consensus` in `_gossipWith`, adding a storage call to store a non-consensus block, writing a database query to check this when we tally roll call votes, and adding an extra database update to flip on the consensus flag in `writeBlock` if it isn't already set.

**Comment by dlongley** [comment]
No longer applicable.
