### ISSUE TITLE
Make sure that all votes in a manifest exists

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#55]
The code here needs to be repositioned.  
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L887

This routine is being called higher up in the stack by a routine that is in the process of storing votes, so the votes could not exist yet.

**Comment by dlongley** [comment]
Hmm, that call should only be checking for event votes -- while certifying a roll-call election. In other words, it shouldn't be circular, it shouldn't be a problem.

When certifying a roll-call election, we need to check to make sure that we have the manifest that was voted on. The manifest contains event votes (not roll-call votes) -- and we need to make sure we have all of these before storing the manifest. Since we're trying to certify a roll-call election, there should be no overlap with storing roll-call votes and checking for event vote existence (because the votes are for different topics).

**Comment by mattcollier** [comment]
@dlongley The stack I referred to earlier:

1. https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L273
2. https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/fa9252514dbdbeb957704cca844c5412772bb7c6/lib/election.js#L814

I notice that at 1, that `_verifyVote` (2) is being called *because* we know the vote does not exist.  From the [check here](https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/fa9252514dbdbeb957704cca844c5412772bb7c6/lib/election.js#L275):

**Comment by dlongley** [comment]
This is valid:

1. Check to see if a *roll-call* vote exists.
2. It doesn't, so verify it.
3. When verifying it, see if you have the manifest the vote is for.
4. You don't, so get it.
5. See if you have the *event* votes for it. (Note: not *roll-call* votes).
6. You don't? It's not verified. You do? Keep running whatever other verification checks.

**Comment by mattcollier** [comment]
@dlongley Need to review with you this process:
1. http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/8eca58765d65c08810f5007b912fc86579a11585/lib/worker.js#L313-L314
2. http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/8eca58765d65c08810f5007b912fc86579a11585/lib/election.js#L246-L247

**Comment by dlongley** [comment]
Fixed by #56.
