### ISSUE TITLE
Disallow empty events

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-ledger-consensus-continuity#77]
In order to ensure that we don't allow attackers to spam the ledger with garbage, we need to check to make sure that empty events are not allowed into the ledger.

The attack is: Some jerk fires up a node, gossip and event with junk operations (that fail operation validation), and then leaves the network forever.

We just need to make sure we don't allow empty events into the ledger.

**Comment by mattcollier** [comment]
@msporny do you think it would be a good idea to put that very basic validation at the ledger-agent level here: https://github.com/digitalbazaar/bedrock-ledger-agent/blob/master/lib/http.js#L300

Sounds like you would like to make sure that `res.body` is not an empty object?  Or are there more very basic validations?

Seems good to me so that we don't have to remember to re-implement basic validation in every consensus algorithm.

**Comment by dlongley** [comment]
@mattcollier,

> Sounds like you would like to make sure that res.body is not an empty object? Or are there more very basic validations?
> 
> Seems good to me so that we don't have to remember to re-implement basic validation in every consensus algorithm.

I think we *have* to specify operation validators for any ledger to be sane. These validators should be what gets invoked when someone tries to write an operation to the ledger. So I think having a check for "its not `{}`" is really that helpful... and it will just be overhead.

However, I thought this issue was about empty events (not operations) ... so I think we're talking about some kind of validation at the gossip HTTP API layer which would be consensus specific?

**Comment by dlongley** [comment]
Closing as addressed or invalid. Empty operations and events are already disallowed and the records within operations must be validated on a ledger-specific basis.
