### ISSUE TITLE
Ensure TLS certificates are checked in production mode on gossip HTTPS API

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#78]

**Comment by mattcollier** [comment]
Are you suggesting something beyond?

 https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/client.js#L21

**Comment by dlongley** [comment]
@mattcollier, perhaps a test? We know that the testnet for veres-one had its TLS certificate expire but gossip continued. Is this normal? Is it a bug? Is it not?

**Comment by mattcollier** [comment]
I just checked the genesis node and it does appear that it is using the production config which does enable strictSSL: https://github.com/veres-one/veres-one/blob/master/configs/production.js#L57

I believe a certificate error would hit this code: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/agents/gossip-agent.js#L90

Which would have simply logged a non-critical error.

When you say 'gossip continued' what do you mean, and what evidence do we have?  I'm wondering because if operations could not be submitted due to certificate errors, what would there be to gossip about?  Are you saying the logs were checked and there was no evidence found for certificate errors during the gossip process?

**Comment by davidlehn** [comment]
Enabled in testnet too:
https://github.com/veres-one/veres-one/blob/master/configs/testnet.js#L58

While the testnet nodes had expired certs I was watching the logs and seeing traffic from the other hosts.  I'm not familiar with what I should have been seeing.  As this was a few days ago, the logs are likely still there.

**Comment by dlongley** [comment]
Old issue now, closing. Addressed by new config/https-agent changes.
