### ISSUE TITLE
Throwing an error instead of passing it to a callback

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#82]
We're throwing an error here (because of some catastrophic problem?)...

https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/d2c7f7c711f5046cede756e79bee77f9d341bde2/lib/events.js#L1527

Is that the best idea? Also, note that it will be handled differently when we move to promises.

**Comment by mattcollier** [comment]
Correct, redis is sort of designed to not produce errors unless there is a catastrophe.  We certainly need more data about what happens if redis fails, and if there is some way of recovering gracefully, that would be good too.  A notification of some kind would be nice because as is, I guess the worker would just get restarted continually.  But in the case of redis failure, the whole system would go down.

**Comment by dlongley** [comment]
We've moved to promises so the error will flow into the same exception stream as anything else. I'm not sure what we need to do here, if anything.

**Comment by dlongley** [comment]
This error has now moved here:

https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/1c45bab6b01774fe39316bb0bcaa35c51cc4431e/lib/cache/events.js#L134

And still needs to be addressed.

**Comment by dlongley** [comment]
The redis cache has been removed for events, this no longer applies.
